// Builds app/vendor/icons.svg: an SVG sprite of the Lucide icons (ISC) the app references.
// Icons are used as <svg class="icon"><use href="./vendor/icons.svg#name"/></svg>, so the
// sprite stays same-origin (CSP-safe) and is precached with the rest of the site.
// lucide-static is a build-time dev dependency only; the generated sprite is committed.
import { readFile, readdir, writeFile, copyFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const APP = path.join(ROOT, 'app');
const LUCIDE = path.join(ROOT, 'node_modules', 'lucide-static');

// Collect icon names referenced in the app sources.
const used = new Set();
for (const name of await readdir(APP)) {
  if (!/\.(html|mjs)$/.test(name)) continue;
  for (const [, icon] of (await readFile(path.join(APP, name), 'utf8')).matchAll(/vendor\/icons\.svg#([a-z0-9-]+)/g)) used.add(icon);
}

const symbols = [];
for (const icon of [...used].sort()) {
  const svg = await readFile(path.join(LUCIDE, 'icons', `${icon}.svg`), 'utf8').catch(() => { throw new Error(`Unknown Lucide icon: ${icon}`); });
  // Keep only the shapes; stroke styling comes from the .icon class on the referencing <svg>.
  const inner = svg.replace(/<!--[\s\S]*?-->/g, '').replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '').trim().replace(/\s*\n\s*/g, '');
  symbols.push(`<symbol id="${icon}" viewBox="0 0 24 24">${inner}</symbol>`);
}

const version = JSON.parse(await readFile(path.join(LUCIDE, 'package.json'), 'utf8')).version;
const sprite = `<svg xmlns="http://www.w3.org/2000/svg">\n<!-- Lucide ${version} (ISC), see LICENSE-lucide.txt. Generated by scripts/build-icons.mjs; do not edit. -->\n${symbols.join('\n')}\n</svg>\n`;
await writeFile(path.join(APP, 'vendor', 'icons.svg'), sprite);
await copyFile(path.join(LUCIDE, 'LICENSE'), path.join(APP, 'vendor', 'LICENSE-lucide.txt'));
console.log(`Icon sprite: ${symbols.length} icons (lucide-static ${version}).`);
